[package]
name = "data_vault_exx"
version = "0.1.0"
edition = "2021"

[dependencies]
argon2 = "0.5.3"
indicatif = "0.17.8"
rand = { version = "0.8.5", features = ["getrandom"] } 
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
termion = "4.0.2"
thiserror = "1.0.63"

