[package]
name = "auth_server"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.3.7"
jsonwebtoken = "7.2"
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
